### ISSUE TITLE
kubeconfig not found 

### ISSUE THREAD

**Issue by ajinkya933** [arjun921/aws-spot-instances-kubeflow#1]
When I run `eksctl create cluster -f envs/$ENVIRONMENT/cluster-spec.yml` I get this error:

```
W0103 23:55:20.550634    2391 loader.go:223] Config not found: /Users/ajinkyabobade/Documents/aws-spot-instances-kubeflow/envs/staging/.kubeconfig
W0103 23:55:20.556414    2391 loader.go:223] Config not found: /Users/ajinkyabobade/Documents/aws-spot-instances-kubeflow/envs/staging/.kubeconfig
W0103 23:55:20.556499    2391 loader.go:223] Config not found: /Users/ajinkyabobade/Documents/aws-spot-instances-kubeflow/envs/staging/.kubeconfig
```

How do I fix this ?

**Comment by arjun921** [comment]
Try switching directory  to `aws-spot-instances-kubeflow` directory and rerunning the command.

If it still doesn't work, 
Could you help me with the output of this command?:
```
echo $KUBECONFIG
```

And let me know which path are you running the create cluster command from.

**Comment by ajinkya933** [comment]
I still get error `unable to use kubectl with the EKS cluster` here are my logs:

% eksctl create cluster -f envs/$ENVIRONMENT/cluster-spec.yml

```
[ℹ]  eksctl version 0.35.0
[ℹ]  using region us-east-2
[ℹ]  subnets for us-east-2a - public:192.168.0.0/19 private:192.168.96.0/19
[ℹ]  subnets for us-east-2b - public:192.168.32.0/19 private:192.168.128.0/19
[ℹ]  subnets for us-east-2c - public:192.168.64.0/19 private:192.168.160.0/19
[ℹ]  nodegroup "ng-1" will use "ami-0516b36ba0c479357" [AmazonLinux2/1.18]
[ℹ]  nodegroup "ng-2" will use "ami-0516b36ba0c479357" [AmazonLinux2/1.18]
[ℹ]  nodegroup "1-gpu-spot-p2-xlarge" will use "ami-07e8aa30939269532" [AmazonLinux2/1.18]
[ℹ]  nodegroup "1-gpu-spot-p3-2xlarge" will use "ami-07e8aa30939269532" [AmazonLinux2/1.18]
[ℹ]  nodegroup "4-gpu-spot-p3-8xlarge" will use "ami-07e8aa30939269532" [AmazonLinux2/1.18]
[ℹ]  using Kubernetes version 1.18
[ℹ]  creating EKS cluster "medium-cluster" in "us-east-2" region with un-managed nodes
[ℹ]  5 nodegroups (1-gpu-spot-p2-xlarge, 1-gpu-spot-p3-2xlarge, 4-gpu-spot-p3-8xlarge, ng-1, ng-2) were included (based on the include/exclude rules)
[ℹ]  will create a CloudFormation stack for cluster itself and 5 nodegroup stack(s)
[ℹ]  will create a CloudFormation stack for cluster itself and 0 managed nodegroup stack(s)
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-east-2 --cluster=medium-cluster'
[ℹ]  CloudWatch logging will not be enabled for cluster "medium-cluster" in "us-east-2"
[ℹ]  you can enable it with 'eksctl utils update-cluster-logging --enable-types={SPECIFY-YOUR-LOG-TYPES-HERE (e.g. all)} --region=us-east-2 --cluster=medium-cluster'
[ℹ]  Kubernetes API endpoint access will use default of {publicAccess=true, privateAccess=false} for cluster "medium-cluster" in "us-east-2"
[ℹ]  2 sequential tasks: { create cluster control plane "medium-cluster", 3 sequential sub-tasks: { tag cluster, create addons, 5 parallel sub-tasks: { create nodegroup "ng-1", create nodegroup "ng-2", create nodegroup "1-gpu-spot-p2-xlarge", create nodegroup "1-gpu-spot-p3-2xlarge", create nodegroup "4-gpu-spot-p3-8xlarge" } } }
[ℹ]  building cluster stack "eksctl-medium-cluster-cluster"
[ℹ]  deploying stack "eksctl-medium-cluster-cluster"
[✔]  tagged EKS cluster (environment=staging)
[ℹ]  building nodegroup stack "eksctl-medium-cluster-nodegroup-ng-2"
[ℹ]  building nodegroup stack "eksctl-medium-cluster-nodegroup-4-gpu-spot-p3-8xlarge"
[ℹ]  building nodegroup stack "eksctl-medium-cluster-nodegroup-1-gpu-spot-p2-xlarge"
[ℹ]  building nodegroup stack "eksctl-medium-cluster-nodegroup-1-gpu-spot-p3-2xlarge"
[ℹ]  building nodegroup stack "eksctl-medium-cluster-nodegroup-ng-1"
[ℹ]  deploying stack "eksctl-medium-cluster-nodegroup-1-gpu-spot-p3-2xlarge"
[ℹ]  deploying stack "eksctl-medium-cluster-nodegroup-ng-1"
[ℹ]  deploying stack "eksctl-medium-cluster-nodegroup-1-gpu-spot-p2-xlarge"
[ℹ]  deploying stack "eksctl-medium-cluster-nodegroup-4-gpu-spot-p3-8xlarge"
[ℹ]  deploying stack "eksctl-medium-cluster-nodegroup-ng-2"
[ℹ]  waiting for the control plane availability...
[✔]  saved kubeconfig as "/Users/ajinkyabobade/Documents/aws-spot-instances-kubeflow/envs/staging/.kubeconfig"
[ℹ]  1 task: { install Nvidia device plugin }
[ℹ]  created "kube-system:DaemonSet.apps/nvidia-device-plugin-daemonset"
[✔]  all EKS cluster resources for "medium-cluster" have been created
[ℹ]  adding identity "arn:aws:iam::412162540872:role/eksctl-medium-cluster-nodegroup-n-NodeInstanceRole-54UT87XYAPUU" to auth ConfigMap
[ℹ]  adding identity "arn:aws:iam::412162540872:role/eksctl-medium-cluster-nodegroup-n-NodeInstanceRole-15R00R0I1Z6EV" to auth ConfigMap
[ℹ]  adding identity "arn:aws:iam::412162540872:role/eksctl-medium-cluster-nodegroup-1-NodeInstanceRole-7W06OK53WH4P" to auth ConfigMap
[ℹ]  as you are using the EKS-Optimized Accelerated AMI with a GPU-enabled instance type, the Nvidia Kubernetes device plugin was automatically installed.
[ℹ]  	 to skip installing it, use --install-nvidia-plugin=false.
[ℹ]  adding identity "arn:aws:iam::412162540872:role/eksctl-medium-cluster-nodegroup-1-NodeInstanceRole-1IPMZQR2AJ6ZY" to auth ConfigMap
[ℹ]  as you are using the EKS-Optimized Accelerated AMI with a GPU-enabled instance type, the Nvidia Kubernetes device plugin was automatically installed.
[ℹ]  	 to skip installing it, use --install-nvidia-plugin=false.
[ℹ]  adding identity "arn:aws:iam::412162540872:role/eksctl-medium-cluster-nodegroup-4-NodeInstanceRole-1DDU4E820CY9F" to auth ConfigMap
[ℹ]  as you are using the EKS-Optimized Accelerated AMI with a GPU-enabled instance type, the Nvidia Kubernetes device plugin was automatically installed.
[ℹ]  	 to skip installing it, use --install-nvidia-plugin=false.
[✖]  unable to use kubectl with the EKS cluster (check 'kubectl --kubeconfig=/Users/ajinkyabobade/Documents/aws-spot-instances-kubeflow/envs/staging/.kubeconfig version'): Unable to connect to the server: getting credentials: exec: fork/exec /usr/local/bin/aws-iam-authenticator: exec format error

[ℹ]  cluster should be functional despite missing (or misconfigured) client binaries
[✔]  EKS cluster "medium-cluster" in "us-east-2" region is ready
```

% echo $KUBECONFIG
```
/Users/ajinkyabobade/Documents/aws-spot-instances-kubeflow/envs/staging/.kubeconfig
```

**Comment by ajinkya933** [comment]
Some additional information:

```
% eksctl version
0.35.0

% kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T08:38:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by arjun921** [comment]
@ajinkya933 Downgrade the kubectl client to 1.18 

and can you check if you have installed 

https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html 
and 
https://docs.aws.amazon.com/eks/latest/userguide/getting-started-console.html#gs-console-install-awscli installed?

**Comment by ajinkya933** [comment]
Is there a way to resolve it without downgrading existing dependencies. As AWS has updated their docs for Kubeflow 1.2 with kfctl_v1.2.0 (https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/). I am using Kubeflow 1.2

**Comment by arjun921** [comment]
@ajinkya933 Kubeflow 1.2 is supported by Kubernetes 1,18
Your client is 1.20, but the cluster is on 1.18

I have faced issues with client version mismatches, and since Kubernetes 1.20 has a few major changes, I think that could be issue.

Personally, my best bet would downgrading the version, I can't think of anything else that could be going wrong.

**Comment by arjun921** [comment]
> I still get error `unable to use kubectl with the EKS cluster` here are my logs:
> 
> % eksctl create cluster -f envs/$ENVIRONMENT/cluster-spec.yml
> 
> ```
> [ℹ]  eksctl version 0.35.0
> [ℹ]  using region us-east-2
> [ℹ]  subnets for us-east-2a - public:192.168.0.0/19 private:192.168.96.0/19
> [ℹ]  subnets for us-east-2b - public:192.168.32.0/19 private:192.168.128.0/19
> [ℹ]  subnets for us-east-2c - public:192.168.64.0/19 private:192.168.160.0/19
> [ℹ]  nodegroup "ng-1" will use "ami-0516b36ba0c479357" [AmazonLinux2/1.18]
> [ℹ]  nodegroup "ng-2" will use "ami-0516b36ba0c479357" [AmazonLinux2/1.18]
> [ℹ]  nodegroup "1-gpu-spot-p2-xlarge" will use "ami-07e8aa30939269532" [AmazonLinux2/1.18]
> [ℹ]  nodegroup "1-gpu-spot-p3-2xlarge" will use "ami-07e8aa30939269532" [AmazonLinux2/1.18]
> [ℹ]  nodegroup "4-gpu-spot-p3-8xlarge" will use "ami-07e8aa30939269532" [AmazonLinux2/1.18]
> [ℹ]  using Kubernetes version 1.18
> [ℹ]  creating EKS cluster "medium-cluster" in "us-east-2" region with un-managed nodes
> [ℹ]  5 nodegroups (1-gpu-spot-p2-xlarge, 1-gpu-spot-p3-2xlarge, 4-gpu-spot-p3-8xlarge, ng-1, ng-2) were included (based on the include/exclude rules)
> [ℹ]  will create a CloudFormation stack for cluster itself and 5 nodegroup stack(s)
> [ℹ]  will create a CloudFormation stack for cluster itself and 0 managed nodegroup stack(s)
> [ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-east-2 --cluster=medium-cluster'
> [ℹ]  CloudWatch logging will not be enabled for cluster "medium-cluster" in "us-east-2"
> [ℹ]  you can enable it with 'eksctl utils update-cluster-logging --enable-types={SPECIFY-YOUR-LOG-TYPES-HERE (e.g. all)} --region=us-east-2 --cluster=medium-cluster'
> [ℹ]  Kubernetes API endpoint access will use default of {publicAccess=true, privateAccess=false} for cluster "medium-cluster" in "us-east-2"
> [ℹ]  2 sequential tasks: { create cluster control plane "medium-cluster", 3 sequential sub-tasks: { tag cluster, create addons, 5 parallel sub-tasks: { create nodegroup "ng-1", create nodegroup "ng-2", create nodegroup "1-gpu-spot-p2-xlarge", create nodegroup "1-gpu-spot-p3-2xlarge", create nodegroup "4-gpu-spot-p3-8xlarge" } } }
> [ℹ]  building cluster stack "eksctl-medium-cluster-cluster"
> [ℹ]  deploying stack "eksctl-medium-cluster-cluster"
> [✔]  tagged EKS cluster (environment=staging)
> [ℹ]  building nodegroup stack "eksctl-medium-cluster-nodegroup-ng-2"
> [ℹ]  building nodegroup stack "eksctl-medium-cluster-nodegroup-4-gpu-spot-p3-8xlarge"
> [ℹ]  building nodegroup stack "eksctl-medium-cluster-nodegroup-1-gpu-spot-p2-xlarge"
> [ℹ]  building nodegroup stack "eksctl-medium-cluster-nodegroup-1-gpu-spot-p3-2xlarge"
> [ℹ]  building nodegroup stack "eksctl-medium-cluster-nodegroup-ng-1"
> [ℹ]  deploying stack "eksctl-medium-cluster-nodegroup-1-gpu-spot-p3-2xlarge"
> [ℹ]  deploying stack "eksctl-medium-cluster-nodegroup-ng-1"
> [ℹ]  deploying stack "eksctl-medium-cluster-nodegroup-1-gpu-spot-p2-xlarge"
> [ℹ]  deploying stack "eksctl-medium-cluster-nodegroup-4-gpu-spot-p3-8xlarge"
> [ℹ]  deploying stack "eksctl-medium-cluster-nodegroup-ng-2"
> [ℹ]  waiting for the control plane availability...
> [✔]  saved kubeconfig as "/Users/ajinkyabobade/Documents/aws-spot-instances-kubeflow/envs/staging/.kubeconfig"
> [ℹ]  1 task: { install Nvidia device plugin }
> [ℹ]  created "kube-system:DaemonSet.apps/nvidia-device-plugin-daemonset"
> [✔]  all EKS cluster resources for "medium-cluster" have been created
> [ℹ]  adding identity "arn:aws:iam::412162540872:role/eksctl-medium-cluster-nodegroup-n-NodeInstanceRole-54UT87XYAPUU" to auth ConfigMap
> [ℹ]  adding identity "arn:aws:iam::412162540872:role/eksctl-medium-cluster-nodegroup-n-NodeInstanceRole-15R00R0I1Z6EV" to auth ConfigMap
> [ℹ]  adding identity "arn:aws:iam::412162540872:role/eksctl-medium-cluster-nodegroup-1-NodeInstanceRole-7W06OK53WH4P" to auth ConfigMap
> [ℹ]  as you are using the EKS-Optimized Accelerated AMI with a GPU-enabled instance type, the Nvidia Kubernetes device plugin was automatically installed.
> [ℹ]  	 to skip installing it, use --install-nvidia-plugin=false.
> [ℹ]  adding identity "arn:aws:iam::412162540872:role/eksctl-medium-cluster-nodegroup-1-NodeInstanceRole-1IPMZQR2AJ6ZY" to auth ConfigMap
> [ℹ]  as you are using the EKS-Optimized Accelerated AMI with a GPU-enabled instance type, the Nvidia Kubernetes device plugin was automatically installed.
> [ℹ]  	 to skip installing it, use --install-nvidia-plugin=false.
> [ℹ]  adding identity "arn:aws:iam::412162540872:role/eksctl-medium-cluster-nodegroup-4-NodeInstanceRole-1DDU4E820CY9F" to auth ConfigMap
> [ℹ]  as you are using the EKS-Optimized Accelerated AMI with a GPU-enabled instance type, the Nvidia Kubernetes device plugin was automatically installed.
> [ℹ]  	 to skip installing it, use --install-nvidia-plugin=false.
> [✖]  unable to use kubectl with the EKS cluster (check 'kubectl --kubeconfig=/Users/ajinkyabobade/Documents/aws-spot-instances-kubeflow/envs/staging/.kubeconfig version'): Unable to connect to the server: getting credentials: exec: fork/exec /usr/local/bin/aws-iam-authenticator: exec format error
> 
> [ℹ]  cluster should be functional despite missing (or misconfigured) client binaries
> [✔]  EKS cluster "medium-cluster" in "us-east-2" region is ready
> ```
> 
> % echo $KUBECONFIG
> 
> ```
> /Users/ajinkyabobade/Documents/aws-spot-instances-kubeflow/envs/staging/.kubeconfig
> ```

Also, based on these logs, it seems likely that your cluster got created succesfully.
But the last line mentioned
 `[ℹ]  cluster should be functional despite missing (or misconfigured) client binaries` points to the Client binary version mismatch.

**Comment by ajinkya933** [comment]
I am removing the cluster and downgrading the kubectl to 1.18. Need to check if this goes smoothly during cluster creation

**Comment by arjun921** [comment]
You won't need to delete the cluster to downgrade your client 😅
Just installing kubectl 1.18 should fix things

**Comment by ajinkya933** [comment]
Downgrading to kubectl 1.18 solved the error during cluster creation 👍 . Cluster is getting created without error: 

But now the error now is during installing Kubeflow :

```
application.app.k8s.io/aws-istio-authz-adaptor configured
adapter.config.istio.io/authzadaptor unchanged
handler.config.istio.io/authzadaptor-handler unchanged
instance.config.istio.io/authzadaptor-instance unchanged
rule.config.istio.io/authzadaptor-rule unchanged
template.config.istio.io/authzadaptor unchanged
WARN[0204] Encountered error applying application aws-istio-authz-adaptor:  (kubeflow.error): Code 500 with message: Apply.Run : unable to recognize "/tmp/kout201469472": no matches for kind "Deployment" in version "extensions/v1beta1"  filename="kustomize/kustomize.go:266"
WARN[0204] Will retry in 3 seconds.                      filename="kustomize/kustomize.go:267"
configmap/aws-authzadaptor-parameters unchanged
service/authzadaptor unchanged
application.app.k8s.io/aws-istio-authz-adaptor configured
adapter.config.istio.io/authzadaptor unchanged
handler.config.istio.io/authzadaptor-handler unchanged
instance.config.istio.io/authzadaptor-instance unchanged
rule.config.istio.io/authzadaptor-rule unchanged
template.config.istio.io/authzadaptor unchanged
WARN[0213] Encountered error applying application aws-istio-authz-adaptor:  (kubeflow.error): Code 500 with message: Apply.Run : unable to recognize "/tmp/kout958015085": no matches for kind "Deployment" in version "extensions/v1beta1"  filename="kustomize/kustomize.go:266"
WARN[0213] Will retry in 6 seconds.                      filename="kustomize/kustomize.go:267"
configmap/aws-authzadaptor-parameters unchanged
service/authzadaptor unchanged
application.app.k8s.io/aws-istio-authz-adaptor configured
adapter.config.istio.io/authzadaptor unchanged
handler.config.istio.io/authzadaptor-handler unchanged
instance.config.istio.io/authzadaptor-instance unchanged
rule.config.istio.io/authzadaptor-rule unchanged
template.config.istio.io/authzadaptor unchanged
WARN[0225] Encountered error applying application aws-istio-authz-adaptor:  (kubeflow.error): Code 500 with message: Apply.Run : unable to recognize "/tmp/kout218596430": no matches for kind "Deployment" in version "extensions/v1beta1"  filename="kustomize/kustomize.go:266"
WARN[0225] Will retry in 5 seconds.                      filename="kustomize/kustomize.go:267"
configmap/aws-authzadaptor-parameters unchanged
service/authzadaptor unchanged
application.app.k8s.io/aws-istio-authz-adaptor configured
adapter.config.istio.io/authzadaptor unchanged
handler.config.istio.io/authzadaptor-handler unchanged
instance.config.istio.io/authzadaptor-instance unchanged
rule.config.istio.io/authzadaptor-rule unchanged
template.config.istio.io/authzadaptor unchanged
WARN[0235] Encountered error applying application aws-istio-authz-adaptor:  (kubeflow.error): Code 500 with message: Apply.Run : unable to recognize "/tmp/kout267180435": no matches for kind "Deployment" in version "extensions/v1beta1"  filename="kustomize/kustomize.go:266"
WARN[0235] Will retry in 9 seconds.                      filename="kustomize/kustomize.go:267"
configmap/aws-authzadaptor-parameters unchanged
service/authzadaptor unchanged
application.app.k8s.io/aws-istio-authz-adaptor configured
adapter.config.istio.io/authzadaptor unchanged
handler.config.istio.io/authzadaptor-handler unchanged
instance.config.istio.io/authzadaptor-instance unchanged
rule.config.istio.io/authzadaptor-rule unchanged
template.config.istio.io/authzadaptor unchanged
WARN[0250] Encountered error applying application aws-istio-authz-adaptor:  (kubeflow.error): Code 500 with message: Apply.Run : unable to recognize "/tmp/kout862213964": no matches for kind "Deployment" in version "extensions/v1beta1"  filename="kustomize/kustomize.go:266"
WARN[0250] Will retry in 12 seconds.  
```

**Comment by ajinkya933** [comment]
Some additional info:

```
% kfctl version
kfctl v1.1.0-0-g9a3621e

```

**Comment by arjun921** [comment]
> Downgrading to kubectl 1.18 solved the error during cluster creation 👍 . Cluster is getting created without error: 
> 
> 
> 
> But now the error now is during installing Kubeflow :
> 
> 
> 
> ```
> 
> application.app.k8s.io/aws-istio-authz-adaptor configured
> 
> adapter.config.istio.io/authzadaptor unchanged
> 
> handler.config.istio.io/authzadaptor-handler unchanged
> 
> instance.config.istio.io/authzadaptor-instance unchanged
> 
> rule.config.istio.io/authzadaptor-rule unchanged
> 
> template.config.istio.io/authzadaptor unchanged
> 
> WARN[0204] Encountered error applying application aws-istio-authz-adaptor:  (kubeflow.error): Code 500 with message: Apply.Run : unable to recognize "/tmp/kout201469472": no matches for kind "Deployment" in version "extensions/v1beta1"  filename="kustomize/kustomize.go:266"
> 
> WARN[0204] Will retry in 3 seconds.                      filename="kustomize/kustomize.go:267"
> 
> configmap/aws-authzadaptor-parameters unchanged
> 
> service/authzadaptor unchanged
> 
> application.app.k8s.io/aws-istio-authz-adaptor configured
> 
> adapter.config.istio.io/authzadaptor unchanged
> 
> handler.config.istio.io/authzadaptor-handler unchanged
> 
> instance.config.istio.io/authzadaptor-instance unchanged
> 
> rule.config.istio.io/authzadaptor-rule unchanged
> 
> template.config.istio.io/authzadaptor unchanged
> 
> WARN[0213] Encountered error applying application aws-istio-authz-adaptor:  (kubeflow.error): Code 500 with message: Apply.Run : unable to recognize "/tmp/kout958015085": no matches for kind "Deployment" in version "extensions/v1beta1"  filename="kustomize/kustomize.go:266"
> 
> WARN[0213] Will retry in 6 seconds.                      filename="kustomize/kustomize.go:267"
> 
> configmap/aws-authzadaptor-parameters unchanged
> 
> service/authzadaptor unchanged
> 
> application.app.k8s.io/aws-istio-authz-adaptor configured
> 
> adapter.config.istio.io/authzadaptor unchanged
> 
> handler.config.istio.io/authzadaptor-handler unchanged
> 
> instance.config.istio.io/authzadaptor-instance unchanged
> 
> rule.config.istio.io/authzadaptor-rule unchanged
> 
> template.config.istio.io/authzadaptor unchanged
> 
> WARN[0225] Encountered error applying application aws-istio-authz-adaptor:  (kubeflow.error): Code 500 with message: Apply.Run : unable to recognize "/tmp/kout218596430": no matches for kind "Deployment" in version "extensions/v1beta1"  filename="kustomize/kustomize.go:266"
> 
> WARN[0225] Will retry in 5 seconds.                      filename="kustomize/kustomize.go:267"
> 
> configmap/aws-authzadaptor-parameters unchanged
> 
> service/authzadaptor unchanged
> 
> application.app.k8s.io/aws-istio-authz-adaptor configured
> 
> adapter.config.istio.io/authzadaptor unchanged
> 
> handler.config.istio.io/authzadaptor-handler unchanged
> 
> instance.config.istio.io/authzadaptor-instance unchanged
> 
> rule.config.istio.io/authzadaptor-rule unchanged
> 
> template.config.istio.io/authzadaptor unchanged
> 
> WARN[0235] Encountered error applying application aws-istio-authz-adaptor:  (kubeflow.error): Code 500 with message: Apply.Run : unable to recognize "/tmp/kout267180435": no matches for kind "Deployment" in version "extensions/v1beta1"  filename="kustomize/kustomize.go:266"
> 
> WARN[0235] Will retry in 9 seconds.                      filename="kustomize/kustomize.go:267"
> 
> configmap/aws-authzadaptor-parameters unchanged
> 
> service/authzadaptor unchanged
> 
> application.app.k8s.io/aws-istio-authz-adaptor configured
> 
> adapter.config.istio.io/authzadaptor unchanged
> 
> handler.config.istio.io/authzadaptor-handler unchanged
> 
> instance.config.istio.io/authzadaptor-instance unchanged
> 
> rule.config.istio.io/authzadaptor-rule unchanged
> 
> template.config.istio.io/authzadaptor unchanged
> 
> WARN[0250] Encountered error applying application aws-istio-authz-adaptor:  (kubeflow.error): Code 500 with message: Apply.Run : unable to recognize "/tmp/kout862213964": no matches for kind "Deployment" in version "extensions/v1beta1"  filename="kustomize/kustomize.go:266"
> 
> WARN[0250] Will retry in 12 seconds.  
> 
> ```
> 
> 
> 
> 

This is normal, let it run
If the kfctl command stops and no longer prints anything, try rerunning. That's how I got mine working.

It retries on failures since it's still waiting for dependent services to go up.

If it still doesn't spin up and go through as expected, you might want to open a thread in Kubeflow.

**Comment by ajinkya933** [comment]
Thank you for help :) I am tracking the issue on: https://github.com/weaveworks/eksctl/issues/3009#issue-777469859. The updated  version of Kubeflow 1.2 is causing errors for scling gpu from zero
